### ISSUE TITLE
Stopped working after 4.5 update!

### ISSUE THREAD

**Issue by zenics** [ThemeFuse/Unyson#1452]
Anyone has the same issue, I ve just updated the wp to 4.5 and Unyson stopped working. i think Its a js problem. I am seeing this on section box function (n){return o.call(this,n,m)}  and nothing shows on pop ups

**Comment by danyj** [comment]
doing it now , will post back

**Comment by moldcraft** [comment]
Update Unyson, we released updates with fixes for wp 4.5

**Comment by danyj** [comment]
looks ok to me , I have latest master. Tested  builder and theme settings , all ok for now.

**Comment by zenics** [comment]
Ok checking it now.

**Comment by zenics** [comment]
It seems to be working guys but still seeing the js error on the title of the section box  function (n){return o.call(this,n,m)} . I have extra settings on framework-customizations folder. Why do you think its there?

**Comment by zenics** [comment]
Never mInd its fixed. thanks guys

**Comment by Undecided90210** [comment]
http://tiny.creativemanner.com/PqWC
The same thing. Updating and CTRL+R - without result 
Need help!

**Comment by tietzmeister** [comment]
I am having the exact same issue as above. I have tried updating the plugin/extension and completely uninstalling Unyson (had to switch themes to do that) and reinstalling it. The display error in the page builder is gone but the Map I put in and some staff images aren't working. I checked to make sure there is no caching plugin and also cleared the browser cache. Still nothing.

No dice. Need some help!
