### ISSUE TITLE
Typography font families

### ISSUE THREAD

**Issue by DevWael** [ThemeFuse/Unyson#1775]
hello guys,
i wonder if there is a way to apply the selected typography font family from google fonts to the front-end to use it with the css

this is my way to do this but i want to know if there is a better way to include the selected google fonts to the front-end

``` php
/*
 * Setup selected google fonts from theme options and add the link to database
 */
add_action( 'fw_settings_form_saved', 'window_process_google_fonts', 999, 2 );
function window_process_google_fonts() {
    if ( function_exists( 'fw_get_db_settings_option' ) ) {
        $include_from_google = array();
        $google_fonts        = fw_get_google_fonts();

        $fonts = array(
            fw_get_db_settings_option( 'site_title/family' ),
            fw_get_db_settings_option( 'tag_line/family' ),
            fw_get_db_settings_option( 'post_title/family' ),
            fw_get_db_settings_option( 'block_widget_title/family' ),
            fw_get_db_settings_option( 'single_post_title/family' ),
            fw_get_db_settings_option( 'single_post_title_cover/family' ),
            fw_get_db_settings_option( 'post_content/family' ),
            fw_get_db_settings_option( 'post_content_homepage/family' ),
            fw_get_db_settings_option( 'small_post_title/family' ),
            fw_get_db_settings_option( 'carousel_post_title/family' ),
            fw_get_db_settings_option( 'read_more_btn/family' ),
            fw_get_db_settings_option( 'error_logo_typo/family' ),
            fw_get_db_settings_option( 'error_message_typo/family' ),
            fw_get_db_settings_option( 'heading_1/family' ),
            fw_get_db_settings_option( 'heading_2/family' ),
            fw_get_db_settings_option( 'heading_3/family' ),
            fw_get_db_settings_option( 'heading_4/family' ),
            fw_get_db_settings_option( 'heading_5/family' ),
            fw_get_db_settings_option( 'heading_6/family' )
        );

        foreach ( $fonts as $font ) {
            if ( isset( $google_fonts[ $font ] ) ) {
                $include_from_google[ $font ] = $google_fonts[ $font ];
            }
        }

        $google_fonts_links = window_get_remote_fonts( $include_from_google );
        // set a option in db for save google fonts link
        update_option( 'window_google_fonts_include', $google_fonts_links );
    }
}

/*
 * Create the google fonts link tag
 */
if ( ! function_exists( 'window_get_remote_fonts' ) ) :
    function window_get_remote_fonts( $include_from_google ) {
        if ( ! sizeof( $include_from_google ) ) {
            return '';
        }
        $html = "<link href='http://fonts.googleapis.com/css?family=";
        foreach ( $include_from_google as $font => $styles ) {
            $html .= str_replace( ' ', '+', $font ) . ':' . implode( ',', $styles['variants'] ) . '%7C';
        }
        $html = substr( $html, 0, - 3 );
        $html .= "' rel='stylesheet' type='text/css'>";

        return $html;
    }
endif;

/*
 * Add google fonts link tag to head tag
 */
add_action( 'wp_head', 'window_google_fonts_link' );
if ( ! function_exists( 'window_google_fonts_link' ) ) :
    function window_google_fonts_link() {
        $google_fonts_link = get_option( 'window_google_fonts_include', '' );
        if ( $google_fonts_link != '' ) {
            echo $google_fonts_link;
        }
    }
endif;

```

**Comment by thednp** [comment]
Why use 30+ google fonts? Isn't that inconsistent design? Not to mention the user experience hustle..

**Comment by eyeswizard** [comment]
you are right, i assigned them all to one value "Montserrat" to prevent the slower load speed,

i wanted to let the user control all possible typography options

**Comment by thednp** [comment]
Yea well, educate your users to not abuse google fonts, load speed is the new SEO critical factor, if your user's user (the end user) leaves the page after 4-6 seconds mark, Google will think that site is 90% irrelevant.

**Comment by eyeswizard** [comment]
aha i will point for that in the theme documentation.

is this way of including google fonts is right ?

i'm asking for feedback, would you like to give me some feedback on my next project (actually this is my second item on themeforest)
the link is [here](https://forums.envato.com/t/whats-your-opinion-i-need-your-feedback-before-submit/55523)

thank you for your help

**Comment by eyeswizard** [comment]
thank you very much :) 
i'm waiting for your review

**Comment by danyj** [comment]
@eyeswizard ,  suggestion , 

This is my array of all google fonts CSS links collected trough all typography options , note that I have custom typo option that makes and saves the links but this is also doable with Unyson default typo

![d519ab069cbc452899a56029fee9a318](https://cloud.githubusercontent.com/assets/2340172/16808112/6e6fd4b0-491b-11e6-9e78-c6f048ebf078.png)


this is the snipp  that gets them all, gets uniques and loads all of them in one line 

		$all_google_fonts = implode( '|', array_unique( THE_ARRAY_IN_THE_IMAGE_ABOVE) );
		$google_font_url  = add_query_arg( 'family', urlencode( $all_google_fonts ), "//fonts.googleapis.com/css" );


this is the print of the `$google_font_url var `


![screenshot_3](https://cloud.githubusercontent.com/assets/2340172/16808211/e1164d3c-491b-11e6-945a-bc5c86c41dd7.jpg)


than I enque it like this 


    wp_enqueue_style( THEME_NAME . '-google-font', esc_url( $google_font_url ), false, null, 'all' );


my complete snipp 



	// Google fonts collection
	if ( isset( ThzDochead::getDocument()->dochead['googlefont'] ) && !empty( ThzDochead::getDocument()->dochead['googlefont'] ) ) {        
        
		$all_google_fonts = implode( '|', array_unique( ThzDochead::getDocument()->dochead['googlefont'] ) );
		$google_font_url  = add_query_arg( 'family', urlencode( $all_google_fonts ), "//fonts.googleapis.com/css" );
		wp_enqueue_style( THEME_NAME . '-google-font', esc_url( $google_font_url ), false, null, 'all' );
	}

**Comment by danyj** [comment]
Forgot ,  this  is the css file I got from  GF
https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&subset=latin%2Clatin-ext&ver=4.5.3

**Comment by danyj** [comment]
Forgot, this is the css file i got from GF 
http://fonts.googleapis.com/css?family=Open+Sans%3Aregular%26subset%3Dlatin%7CLato%3Aregular%26subset%3Dlatin%7CJura%3Aregular%26subset%3Dlatin%7COpen+Sans%3A600%26subset%3Dlatin

**Comment by eyeswizard** [comment]
Thank you @danyj 
but it seems you limit the font options to the array you provided and don't allow the user to select the fonts from all google fonts available.

**Comment by thednp** [comment]
@danyj I think your link is not correct, it should point to this

```
http://fonts.googleapis.com/css?family=[FONTFAMILY]:[VARIANTS]|[FONTFAMILY]:[VARIANTS]&subsets=[ALL_FONTS_SUBSETS]
```

**Comment by danyj** [comment]
nope , they can select all 600+ ,  
http://take.ms/OK6a8


@thednp 
https://www.google.com/fonts#QuickUsePlace:quickUse

is correct 

`Open+Sans:400italic&subset=latin,greek `  // 400,    or regular works also

**Comment by thednp** [comment]
Yes, but when you didn't get my point. If you have more than one font in the `<link>` request, that's the way to go.

**Comment by danyj** [comment]
@thednp   or if you meant because i did opensansset + juraset + latoset +  opensanset , I tested that to , and works , see the link
http://fonts.googleapis.com/css?family=Open+Sans%3Aregular%26subset%3Dlatin%7CLato%3Aregular%26subset%3Dlatin%7CJura%3Aregular%26subset%3Dlatin%7COpen+Sans%3A600%26subset%3Dlatin


it loads whats needed ,   open sans 400 and 600  plus Lato and Jura , 

I did not want to "massage"  the array and pull things out since it works either way , set + set , or set + weight + weight

**Comment by thednp** [comment]
Here's a paste from Google
```html
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,800,600|Roboto+Slab:400,300,700&subset=latin,greek-ext,latin-ext' rel='stylesheet' type='text/css'>
```

look at it closely.

**Comment by eyeswizard** [comment]
You will need to encode the `|`.
the W3 validator will notice you with the error (Bad Value).
Replace it with `%7C`

**Comment by danyj** [comment]
@eyeswizard  , 
>You will need to encode the |.

thus  the   urlencode( $all_google_fonts )  in the snipp

**Comment by eyeswizard** [comment]
@danyj  thank you, i updated my code with it.

**Comment by zenics** [comment]
Is there a way to limit the google fonts to be 4? I only need to show 4 that I select to show on typography 2.

**Comment by zenics** [comment]
@GheorgheP I dont get what I do with this. Can you give me a little bit direction for what i am trying to do?

**Comment by GheorgheP** [comment]
Ok, but this would require some technical knowledge.

The fact is that you receive a list of fonts from google and you have to filter them and get only the needed ones.

```php
function fw_is_right_font( $font ) {
	static $fonts = array( 'lato', 'open sans' );

	return in_array( strtolower( $font['family'] ), $fonts );
}

function _filter_filter_fonts( $fonts ) {
	return fw_aks(
		'items',
		array_filter( $fonts['items'], 'fw_is_right_font' ),
		$fonts
	);
}

add_filter( 'fw_option_type_typography_v2_google_fonts', '_filter_filter_fonts' );
```

In the `fw_is_right_font()` function you need to replace the fonsts names of the `$fonts` variable with your desired fonts names.

**Comment by zenics** [comment]
I just try this in the child themes function.php file and on the theme settings page I still get the full list. What am I doing wrong?

**Comment by GheorgheP** [comment]
It doesn't work because we solution for this was't released yet. But if you are using The Core theme you may not get this functionality at all, from what I know the theme uses it's own `typography` option type, you need to get in touch with [ThemeFuse Techical Support](http://support.themefuse.com/hc/en-us/requests/new) guys and they will help you with that.
