### ISSUE TITLE
Cannot activate hidden standalone extension Shortcodes

### ISSUE THREAD

**Issue by bkramsay** [ThemeFuse/Unyson#220]
I have installed the Unyson plugin but whenever I try to install an extension through the Unyson panel, I get

Cannot activate hidden standalone extension Shortcodes

any help much appreaciated

**Comment by bkramsay** [comment]
I also get 
Fatal error: Class 'FW_Option_Type_Builder' not found in ...wordpress\wp-content\plugins\unyson\framework\extensions\forms\includes\option-types\form-builder\class-fw-option-type-form-builder.php on line 8

when installing the form plugin

**Comment by moldcraft** [comment]
> I also get 
> Fatal error: Class 'FW_Option_Type_Builder' not found in ...wordpress\wp-content\plugins\unyson\framework\extensions\forms\includes\option-types\form-builder\class-fw-option-type-form-builder.php on line 8
>
> when installing the form plugin

Sorry, the Forms extension must be hidden. Please update to unyson 2.1.21, we fixed that (made it hidden).

> I have installed the Unyson plugin but whenever I try to install an extension through the Unyson panel, I get
> 
> Cannot activate hidden standalone extension Shortcodes
> 
> any help much appreaciated

This happens with any extension?

**Comment by bkramsay** [comment]
hi, I updated to 2.1.21 and re-installed Page Builder and get

Warning: require(C:\Users\bkram_000\Dropbox (CI)\Websites\htdocs\colordarcy\wordpress\wp-content\plugins\unyson\framework\extensions\shortcodes\extensions\page-builder\includes\fw-option-type-page-builder\includes\items-corrector/class-page-builder-items-corrector-row-container.php): failed to open stream: Invalid argument in ...\htdocs\colordarcy\wordpress\wp-content\plugins\unyson\framework\extensions\shortcodes\extensions\page-builder\includes\fw-option-type-page-builder\includes\items-corrector\class-page-builder-items-corrector.php on line 226

Fatal error: require(): Failed opening required '..\htdocs\colordarcy\wordpress\wp-content\plugins\unyson\framework\extensions\shortcodes\extensions\page-builder\includes\fw-option-type-page-builder\includes\items-corrector/class-page-builder-items-corrector-row-container.php' (include_path='.;C:\xampp\php\PEAR') in C:\Users\...htdocs\colordarcy\wordpress\wp-content\plugins\unyson\framework\extensions\shortcodes\extensions\page-builder\includes\fw-option-type-page-builder\includes\items-corrector\class-page-builder-items-corrector.php on line 226

**Comment by bkramsay** [comment]
Okay I have fixed that
The problem was the length of the file names on windows machine.

I have shortened the folder names of my installation but probably worth looking at.

Thank you for your help

**Comment by bkramsay** [comment]
Still get 
"Cannot activate hidden standalone extension Contact Forms"
once page builder installed

**Comment by moldcraft** [comment]
> The problem was the length of the file names on windows machine.

Maybe you can find a way to increase the file length limit?
