### ISSUE TITLE
Demo content install issue: The execution failed. Please check error.log

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2257]
I have tried to install demo content one my server. but the problem is an error showing when tried to install demo content.
![hello](https://puu.sh/sP0GW/73fac81374.png)

I have set max execution time 500 but the still same issue and no error details found except mysql_connect() deprecated notice. 

I have tried with debug: true and debug_log true. Nothing there.

**Comment by moldcraft** [comment]
Hello,

Send please your admin and ftp credentials to `moldcraft[at]email.com`

**Comment by Ataurr** [comment]
I have sent Login details to your email.

**Comment by moldcraft** [comment]
I changed [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/f4f372a3c144d38318b393f586b8acabbb74d332/includes/module/tasks/type/class-fw-ext-backups-task-type-image-sizes-restore.php#L68) `-10` to `-20` and demo install has finished.

**Comment by Ataurr** [comment]
@moldcraft  I think you should set to 20 default.  I am getting this issue others server too. So I have to manually set 20 to install demo content.

**Comment by philgoon** [comment]
I'm still having the same issue even though this is set to 20 by default. Any workaround!!

**Comment by Ataurr** [comment]
Hello,

Please Send your admin and ftp credentials to moldcraft[at]email.com

**Comment by Caslavinieri** [comment]
same issue, tried everything i know, calling go daddy whole day...

**Comment by GheorgheP** [comment]
At what step is returns this error?

**Comment by Caslavinieri** [comment]
at the very end maybe 4/5th of process...

**Comment by GheorgheP** [comment]
At Files restore or Image Size Restore? This is very important to know.

**Comment by Caslavinieri** [comment]
Local Download

**Comment by Caslavinieri** [comment]
now it happens on different stages...

**Comment by GheorgheP** [comment]
Try to increase the [php timeout limit](http://php.net/manual/de/function.set-time-limit.php).

**Comment by Caslavinieri** [comment]
3 mins ago Files Export: The execution failed. Please check error.log
7 mins ago Files Export: The execution failed. Please check error.log
11 mins ago Files Export: The execution failed. Please check error.log
15 mins ago Download: The execution failed. Please check error.log
31 mins ago Files Export: The execution failed. Please check error.log
1 hour ago Files Restore: The execution failed. Please check error.log
2 hours ago Download: The execution failed. Please check error.log
2 hours ago Download: The execution failed. Please check error.log
2 hours ago Download: The execution failed. Please check error.log

**Comment by Caslavinieri** [comment]
I have added .user.ini

max_execution_time = 300
max_file_uploads = 120
post_max_size = 32M 
memory_limit = 128M
upload_max_filesize = 32M
post_max_size = 32M

but still no progress

**Comment by Caslavinieri** [comment]
hello, i am so flustrated on this one...

**Comment by GheorgheP** [comment]
Please provide a link to your site, dashboard login details and ftp/CPanel details on `pisarenco.gh[[at]]gmail.com`, and I will take a look.

**Comment by Caslavinieri** [comment]
thanks! Hopefully problem was resolved in the morning, go daddy hosting in "Deluxe" version seems to be very slow, and solution was to change max_execution_time on 500 and max_input_time on -1 provided by ThemeBloossom which i am very thankful!

**Comment by GheorgheP** [comment]
This sounds good.
Like I mentioned, it was from `max_input_time`, as this depends on the sever capabilities, and at the monet we do not have a solution to speedup the process on slow servers.

**Comment by PalThemes** [comment]
Hello, i have same problem with message "The execution failed. Please check error.log"
It's failed while "Files Export" (and sometimes while "Archive Zip")
Please help me.

**Comment by GheorgheP** [comment]
You are doing Full backup or Content? This is important because it fails on file export and Archive zip usually in full backup and from same problem. The full backup backups the entire `wp-content` folder and sometimes users have there a lot of "trash" like backups from other plugins, cache ... Some times other plugins backups are really huge 2-4GB. You have to make sure that you do not have the same problem.

**Comment by PalThemes** [comment]
I'm doing Content Backup.
The file size just around 70MB. I've try installing demo content both from remote server install and local install but still have a same problem.
This problem only occurs on my client's website, he's using turhost. I think the problem occurs caused by server configurations, but i can't figuring out what's the problem, i've tried changing php.ini settings, but still doesn't work.
And now i really frustrated with this.

**Comment by GheorgheP** [comment]
Ddi you activate the `WP_DEBUG_LOG` to checkout for errors?
Also did you increase the timeout?

I had once a very interesting scenario on a client's hosting, his disk limit was 400Mb and he used about 350, and when he tried to make a backup, that was about 100Mb, the result was the same, as hi reached the disk limit.

**Comment by PalThemes** [comment]
I got this messages.
```
[12-Apr-2017 06:26:06 UTC] PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at /home/gurkanac/public_html/wp-includes/functions.php:3719) in /home/gurkanac/public_html/wp-content/plugins/unyson/framework/includes/hooks.php on line 228
[12-Apr-2017 06:26:07 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/gurkanac/public_html/wp-includes/functions.php:3719) in /home/gurkanac/public_html/wp-content/plugins/unyson/framework/includes/hooks.php on line 228
```
I think the problem not on disk limit, because my client using unlimited disk space hosting package.
I have increased max_execution_time to 120000 and max_input_time to -1.

After i cleaning up "wp-content/uploads" folder, i got new error, now it's stuck on "Files Restore".

**Comment by GheorgheP** [comment]
Wait, you are doing content backup or backup restore?

**Comment by PalThemes** [comment]
I'm doing "Demo Content Install"

**Comment by PalThemes** [comment]
![screenshot-www gurkanacka com-2017-04-12-13-48-09](https://cloud.githubusercontent.com/assets/9628687/24944787/ca6dbd58-1f86-11e7-9ce8-337d8d986ab5.png)

**Comment by PalThemes** [comment]
![2222](https://cloud.githubusercontent.com/assets/9628687/24945069/07fe5bf4-1f88-11e7-946f-b20ecdf35bb0.png)

**Comment by nik614** [comment]
Has this been resolved?  I am getting the same issue on the same step with the same theme.

**Comment by PalThemes** [comment]
@nik614 Did you using Assez theme? You can contact our support team deo.hoshi@gmail.com

**Comment by webasbil** [comment]
Hi there. I'm still having the same issue even though this is set to -20 by default and my php files settings
max_execution_time | 5000
max_input_time | -1
memory_limit | 128M
open_basedir | no value
post_max_size | 128M
upload_max_filesize | 256M
i checked my log files but nothing else.

**Comment by Ataurr** [comment]
@PalThemes  How you solved this issue?

**Comment by webasbil** [comment]
Nope its going on

**Comment by webasbil** [comment]
piecemeal.zip and database.json.text file fully can not unzip on FTP

https://drive.google.com/open?id=0B2OnL3PnoFeTQjFFaUg2Ym1jbFE

**Comment by romano88** [comment]
hi i installed a theme called unicum and when i try to install the demo content it gives an error like "Files Export: The execution failed. Please check error.log" when go and check error log it says the same what do i have to do i can not install the demo please help urgent... pls pls pls :)

**Comment by ViorelEremia** [comment]
You've tried all the steps from above comments?

**Comment by romano88** [comment]
@ViorelEremia Yes i did try it but it still don't work don't know what to do next...

**Comment by PalThemes** [comment]
@Ataurr No, I can't solve this issue, last I meet our buyer with this issue, I give up and finally I must installs all demo data on our buyer's website "manually". And that is very a painful process :(

**Comment by ViorelEremia** [comment]
ThemeFuse/Unyson-Backups-Extension@f8d5f6a...841413f

**Comment by capzman** [comment]
Hi Guys,
I have similar issue with this using CrowdmercWordpressTheme

**Comment by SMKH-PRO** [comment]
Same isssue 👎  facing with marketo theme

**Comment by Ataurr** [comment]
@capzman and @SMKH-PRO  Contact the theme author...

**Comment by hitechtecnology** [comment]
I have tried to install demo content one my server. but the problem is an error showing when tried to install demo content.
The execution failed. Please check error.log

**Comment by Tibertius** [comment]
> Same isssue 👎 facing with marketo theme

did you resolve this issue

**Comment by Ataurr** [comment]
HI @Tibertius  

Contact the theme author about this issue.

**Comment by seliasroca** [comment]
Same problem here. I tried everything but cant get teh demo content.

**Comment by faboar** [comment]
I was having the same problem. It was solved in a way that does not seem so logical to me. However I share it in case someone finds it useful. I found the solution because I managed three WP sites and only one of them allowed me to install the Demo content. The difference between the sites was SSL enabled. So I activated the SSL and demo content installation worked fine.

My environment:
Hosting: Hostinger
Theme: Ustudi
Page builder: Unyson
WP versión 5.7


good luck

**Comment by karan-archway** [comment]
Getting same error
i'm new to this can someone help me step by step to change execution time?
Thanks in advance

**Comment by kaushikkini** [comment]
@faboar You are amazing in the workaround! It did work in my case after I activated my SSL with Hostinger. Definitely worth a try if someone is not able to import demo content (due to some weird errors). Just try activating SSL and importing again!

Happy Wordpressing!

**Comment by 1amine3** [comment]
I have a problem downloading the demo too, please help me with a solution

**Comment by 1amine3** [comment]
This message appears to me 
Thé exécution faibles please check error.log

**Comment by tejkhatriremote** [comment]
Hello 
I faced the same issue I m using php 8.1 with I have set below configuration in my wordpress's wp-config.php file

// Set WP Memory Limit
define('WP_MEMORY_LIMIT', '512M');

// Set Upload Max. Filesize
@ini_set('upload_max_filesize','256M');

// Set Max. Post Size
@ini_set('post_max_size','128M');

// Set Max. Execution Time
@ini_set('max_execution_time', '120000');

// Set PHP Max. Input Vars
@ini_set('max_input_vars', '8000');

// Set PHP Max. Input Time
@ini_set('max_input_time', '-1');

I need help . let me know
