### ISSUE TITLE
Critical PHP Issue: An active PHP session was detected.

### ISSUE THREAD

**Issue by jmhmedia** [ThemeFuse/Unyson#4048]
I'm getting the following error in my Site Health settings. After deactivating ALL plugins and reactivating one by one, I found that Unyson is the culprate. 

> A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.

**Comment by jeremyJJB** [comment]
I have the exact same issue with WP 5.5.1 and Unyson 2.7.24

**Comment by wholthof** [comment]
And I have the exact same issue with WP 5.5.1 and Unyson 2.7.24 and have remove Unyson than no problem.
Please give me the solution

**Comment by franckadil** [comment]
Can Reproduce on latest 2.7.24: A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.

**Comment by franckadil** [comment]
@jmhmedia , @jeremyJJB , @wholthof Hi guys, I made some pull requests, please review and suggest corrections if you can:

#4052
#4051

The best,

**Comment by wholthof** [comment]
Hi,

 

I have modify the 2 files but now I canot startup the website.

After I change to the old situation I can startup my website

 

Please give a good tested update from Unyson.

 

 

Met vriendelijke groeten,
 
Wim Holthof
 
 
Deurzerdiep 30 | 8032 NA | Zwolle 
................................................................
Wim Holthof
'   06 112 39503
E-mail:  <mailto:wholthof@home.nl> wholthof@home.nl

 

 

 

 

Van: Franck Adil Koumba [mailto:notifications@github.com] 
Verzonden: vrijdag 11 september 2020 16:42
Aan: ThemeFuse/Unyson <Unyson@noreply.github.com>
CC: wholthof <wholthof@home.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ThemeFuse/Unyson] Critical PHP Issue: An active PHP session was detected. (#4048)

 

@jmhmedia <https://github.com/jmhmedia>  , @jeremyJJB <https://github.com/jeremyJJB>  , @wholthof <https://github.com/wholthof>  Hi guys, I made some pull requests, please review and suggest corrections if you can:

#4052 <https://github.com/ThemeFuse/Unyson/pull/4052> 
#4051 <https://github.com/ThemeFuse/Unyson/pull/4051> 

The best,

**Comment by wholthof** [comment]
Hi,
I have modify the 2 files but now I canot startup the website.
After I change to the old situation I can startup my website
Please give a good tested update from Unyson.

**Comment by jeremyJJB** [comment]
@franckadil I took a look at the code it looks like everything is closed. Full disclosure I'm not an expert in PHP or WP plugin dev. Going off what @wholthof mentioned in his previous comment, it seems that one too many sessions have been closed since the site would not load but I'm not sure. Thank you for taking the initiative on this. I've been having a lot of headaches with Unyson lately.

**Comment by wholthof** [comment]
My workarround is add in below 
in  themes/xxxx/funtions.php 
if (!function_exists('_disable_fw_use_sessions')) { add_filter('fw_use_sessions','_disable_fw_use_sessions'); function _disable_fw_use_sessions(){ return false; } }

AGAIN THE URGENT REQUEST THAT UNYSON RELEASES AN UPDATE ASAP !!!!!!!

**Comment by wholthof** [comment]
Please can you tell me when Unyson release an update!!!

**Comment by marymaru** [comment]
Same here:

> An active PHP session was detected. A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.
> 
> I've talked to my web host and they've confirmed it's the Unyson plugin that's initiating the session. When they deactivated the plugin (and crashed my site) the PHP error disappeared. I tried deleting Unyson and then reinstalling on a dev site and it caused massive corruption to my site.

@wholthof workaround 👍🏻 thanks!
**Adding to the urgent requests for a Unyson update.**

**Comment by Ataurr** [comment]
@valeriuzdrobau @andreiglingeanu @ViorelEremia @GheorgheP @llemurya @sergiu-radu Can you Please release an update with this fix?

**Comment by luseju** [comment]
Hi! I'm having the same error, and now I can't access into my WP site.

**Comment by corzel** [comment]
I fixed it adding: 
**session_write_close();** 
in lines 231 and 262 in this file: wp-content/plugins/unyson/framework/includes/hooks.php
```
229: session_start();
230: }
231: session_write_close();
232: }

**Comment by wholthof** [comment]
WHY DOES UNYSON NOT ISSUE AN UPDATE THAT SOLVES THIS PROBLEM ???
Surely this is not always the case that everyone is looking for a solution.
Unyson come up with that Update

**Comment by CMRD77** [comment]
Is there any solution or update yet?.

> "A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests."

**Comment by apatsidis123** [comment]
Same here, is December and Unyson Still didnt fix that issue? come on guys its a security issue are you serius? So many Themes are dependent from that, please fix your issues!

**Comment by yaaax** [comment]
Same here.
From what I understand, Unyson plugin uses the session to store "[Flash messages](http://manual.unyson.io/en/latest/helpers/flash-messages.html)".
See file `/framework/helpers/class-fw-flash-messages.php`:
> Store messages in session (to not be lost between redirects) and remove them after they were shown to the user

Some useful links :
- ["Avoid using sessions"](https://github.com/ThemeFuse/Unyson/issues/2582)
- ["WordPress Cookies and PHP Sessions – Everything You Need to Know"](https://kinsta.com/blog/wordpress-cookies-php-sessions/#php-sessions) _(-> "We don’t recommend using PHP sessions")_

@ViorelEremia you seem to be the developer who would know the best how to rework this _Flash Messages_ mechanism without sessions (see ["Unyson not playing nice with Varnish-caching"](https://github.com/ThemeFuse/Unyson/issues/3269))
You actually introduced the workaround to disabled sessions : ["add hook to disable sessions"](https://github.com/ThemeFuse/Unyson/commit/123882504aaa8cdd3bf6deec3e39ea62cd1d3b1b).

I think it's time for your bosses to give you some time to think about a rework :)
Have a great New Year's Eve.

Cheers

**Comment by EddiebNZ** [comment]
It's February and still no fix.

**Comment by jascha030** [comment]
We are still experiencing this issue.
Any activity still going on here? And if not, is there a possibility to implement a fix and make a pullrequest ourselves?

**Comment by wholthof** [comment]
Hey

 

Onderstaande heb ik nu na aanpassing in hooks.php op aktief

in lines 231 and 262 in this file: wp-content/plugins/unyson/framework/includes/hooks.php

229: session_start();

230: }

231: session_write_close();

232: }

 

Maar blijft een workarround en snap niet waarop er geen update komt

 

 

Met vriendelijke groeten,
 
Wim Holthof
 
 
Deurzerdiep 30 | 8032 NA | Zwolle 
................................................................
Wim Holthof
'   06 112 39503
E-mail:  <mailto:wholthof@home.nl> wholthof@home.nl

 

 

 

Van: Jascha van Aalst <notifications@github.com> 
Verzonden: vrijdag 5 maart 2021 16:25
Aan: ThemeFuse/Unyson <Unyson@noreply.github.com>
CC: wholthof <wholthof@home.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ThemeFuse/Unyson] Critical PHP Issue: An active PHP session was detected. (#4048)

 

We are still experiencing this issue.
Any activity still going on here? And if not, is there a possibility to implement a fix and make a pullrequest ourselves?

**Comment by corzel** [comment]
This is the new (official) fix Click here
<https://github.com/ThemeFuse/Unyson/pull/4052/commits/da578e754381632b27289be3d92c1a3cc7f1d14f>
.

**Comment by EddiebNZ** [comment]
> This is the new (official) fix Click here <[da578e7](https://github.com/ThemeFuse/Unyson/pull/4052/commits/da578e754381632b27289be3d92c1a3cc7f1d14f)> . El vie, 5 de mar. de 2021 a la(s) 11:05, wholthof (notifications@github.com) escribió:

Thank you, though I believe that has an error in it at line 260 where there is an unrequired } in the code

`session_start();
			}      /** This shouldn't be here
			       /**
		                * PHP sessions created with session_start() function may cause issues with REST API and loopback requests due to cURL error 28. 
		 		* @internal
				*/
				session_start(['read_and_close' => true,]);
			} 
		}`

**Comment by wholthof** [comment]
Hey,

 

The official fix <da578e7> is not working for me. Can't start the website.
I go back to my solution that solves the problem

 



 



 

 

Met vriendelijke groeten,
 
Wim Holthof
 
 
Deurzerdiep 30 | 8032 NA | Zwolle 
................................................................
Wim Holthof
'   06 112 39503
E-mail:  <mailto:wholthof@home.nl> wholthof@home.nl

 

 

 

 

Van: EddiebNZ <notifications@github.com> 
Verzonden: zaterdag 6 maart 2021 06:42
Aan: ThemeFuse/Unyson <Unyson@noreply.github.com>
CC: wholthof <wholthof@home.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ThemeFuse/Unyson] Critical PHP Issue: An active PHP session was detected. (#4048)

 

This is the new (official) fix Click here <da578e7 <https://github.com/ThemeFuse/Unyson/pull/4052/commits/da578e754381632b27289be3d92c1a3cc7f1d14f> > . El vie, 5 de mar. de 2021 a la(s) 11:05, wholthof (notifications@github.com <mailto:notifications@github.com> ) escribió:

Thank you, though I believe that has an error in it at line 260 where there is an unrequired } in the code

session_start(); } /** This shouldn't be here /** * PHP sessions created with session_start() function may cause issues with REST API and loopback requests due to cURL error 28. * @internal */ session_start(['read_and_close' => true,]); } }

**Comment by wholthof** [comment]
The official fix <da578e7> is not working for me. Can't start the website.
I go back to my solution that solves the problem

 in lines 227 and 259 in this file: wp-content/plugins/unyson/framework/includes/hooks.php
229: session_start();
230: }
231: session_write_close();
232: }

**Comment by EddiebNZ** [comment]
See my comment above, the official fix has an extra } that shouldn't be in there, if you remove that the fix works, but it doesn't stop the PHP sessions error being listed in the Site Health screen.

> The official fix is not working for me. Can't start the website.
> I go back to my solution that solves the problem
> 
> in lines 227 and 259 in this file: wp-content/plugins/unyson/framework/includes/hooks.php
> 229: session_start();
> 230: }
> 231: session_write_close();
> 232: }

**Comment by apatsidis123** [comment]
if it is an official fix why they do not deploy an official update so we can update it as all other wordpress plugins, so we are sure that it works for everyone?

**Comment by wholthof** [comment]
Daar ben ik het mee eens. Dit is toch geen offciële oplossing maar geknoei met de beste bedoeling natuurlijk

**Comment by wholthof** [comment]
Hey,

 

My workaround is no longer showing active PHP session notifications. Isn't it better to use?

 

Wim

 

Van: EddiebNZ <notifications@github.com> 
Verzonden: zondag 7 maart 2021 23:48
Aan: ThemeFuse/Unyson <Unyson@noreply.github.com>
CC: wholthof <wholthof@home.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ThemeFuse/Unyson] Critical PHP Issue: An active PHP session was detected. (#4048)

 

See my comment above, the official fix has an extra } that shouldn't be in there, if you remove that the fix works, but it doesn't stop the PHP sessions error being listed in the Site Health screen.

The official fix is not working for me. Can't start the website.
I go back to my solution that solves the problem

in lines 227 and 259 in this file: wp-content/plugins/unyson/framework/includes/hooks.php
229: session_start();
230: }
231: session_write_close();
232: }

**Comment by apatsidis123** [comment]
For me indeed no longer showing the notiication but i got 50 errors on chrome's developer tool on console, so i return to the official official!!!

**Comment by wholthof** [comment]
Oke,  works the official fine without problems?

Can you mail my a screenshot from the official

Wim

Van: apatsidis123 ***@***.***> 
Verzonden: maandag 8 maart 2021 19:13
Aan: ThemeFuse/Unyson ***@***.***>
CC: wholthof ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [ThemeFuse/Unyson] Critical PHP Issue: An active PHP session was detected. (#4048)

 

For me indeed no longer showing the notiication but i got 50 errors on chrome's developer tool on console, so i return to the official official!!!

**Comment by EddiebNZ** [comment]
I've now moved off my Unyson based theme (Woffice) and all the issues I was having with my site have gone away. Whether it was Unyson or the Theme I don't know but I don't think I'll be going back.

**Comment by wholthof** [comment]
Unyson moet nog STEEDS een goedwerkende patch toeleveren, maar mijn workarround lost het probleem ook op. Ik denk dus dat het ook aan jou thema kan liggen dat je problemen blijft houden. Het is toch niet normaal dat Unyson niet van zich laat horen !!!!

**Comment by jascha030** [comment]
> Unyson moet nog STEEDS een goedwerkende patch toeleveren, maar mijn workarround lost het probleem ook op. Ik denk dus dat het ook aan jou thema kan liggen dat je problemen blijft houden. Het is toch niet normaal dat Unyson niet van zich laat horen !!!!

I'm responding in English out of courtesy towards others,
From hearsay I've understood that active development to Unyson has probably stopped. It was part of ThemeFuse which they have stated is now deprecated. I'm not too invested, this question was not one that came from myself, and I did no research whatsoever on the situation.

I can see their frustration caused by breaking Wordpress updates as a good reason to stop active development. In my opinion they can't really be held accountable for the deprecation. 
What I however do think they should be held accountable for, is the lack of a clear statement in the README's of their themefuse Repo's. 

I think they're smudging their own name by leaving people hung out to dry like this...

From what I've seen, my suggestion would be to contact them through their support for their current project: [https://support.brizy.io](https://support.brizy.io).

That being said, I wouldn't expect too much out of their response and start thinking about abandoning it all together. Trying to maintain a deprecated framework is asking for issues in the long term (especially when PHP 8 is moving towards being the new standard). 
Also Wordpress + old plugins/themes is an open invitation to hackers.

It sucks but it's also the nature of software... 

Hope this has been somewhat helpful information to anyone in this thread, if not for fixing it, maybe just for managing expectations. Good luck!

**Comment by omniacode** [comment]
> My workarround is add in below
> in themes/xxxx/funtions.php
> if (!function_exists('_disable_fw_use_sessions')) { add_filter('fw_use_sessions','_disable_fw_use_sessions'); function _disable_fw_use_sessions(){ return false; } }
> 
> AGAIN THE URGENT REQUEST THAT UNYSON RELEASES AN UPDATE ASAP !!!!!!!

Just inherited a site that is using Unyson and can confirm that is it the cause for this error, and the above workaround from @wholthof does in fact "fix" it. Bringing this to the client's attention in hopes that we can get them out of the theme they are using and this awful plugin. Goota love when developers just decide to up and quit a project and leave everyone out to dry. Just horrible.

**Comment by jakubkasparek** [comment]
> This is the new (official) fix Click here <[da578e7](https://github.com/ThemeFuse/Unyson/pull/4052/commits/da578e754381632b27289be3d92c1a3cc7f1d14f)> . El vie, 5 de mar. de 2021 a la(s) 11:05, wholthof (notifications@github.com) escribió:
> […](#)

thanks, this changes help.
