### ISSUE TITLE
Failed to access Github repository (cURL error 28: Connection timed out after 5000 milliseconds)

### ISSUE THREAD

**Issue by chrisbutler** [ThemeFuse/Unyson#4249]
This appears to be happening with some extensions but not others. I have tested with multiple Wordpress installs (6.0, 5.4, 4.8) and see the same issue across all of them. I do not have any issues `curl`-ing from other sites

Lists below are a sample of what I have tested:

### Extensions that download successfully
- Translate Press

### Extensions that fail to download
- Backup & Demo Content
- Sliders
- SEO
- Analytics

**Comment by JustinGuese** [comment]
same, 
```
Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
````

**Comment by letas89** [comment]
The same issue. Failed to access Github repository (cURL error 28: Connection timed out after 5000 milliseconds). The extensions did not istalled.

**Comment by starterfm** [comment]
I am also finding this issue, however it seems to be coming from the root issue that the download location "https://github-api-cache.unyson.io/" is currently down.

**Comment by annabellecloete** [comment]
I had the same issue, manually by uploading the extensions directly to my files..
[extensions.zip](https://github.com/ThemeFuse/Unyson/files/9174005/extensions.zip)
.

**Comment by JustinGuese** [comment]
Hi @annabellecloete , could you specify to where exactly you uploaded it? I tried wp-content/plugins/ but it doesn't work

**Comment by annabellecloete** [comment]
public_html/wp-content/plugins/unyson/framework/extensions
Make sure you unzip the specific extensions within the extensions folder :)

**Comment by JustinGuese** [comment]
hmm kind of fixes it a little bit for me, thanks! still missing the "import demo" option for me, but at least the backup option shows now...

For anyone that wants to fix it temporarily until the "probably" will fix it (or not, this issue exists since 2017)
1. ssh into your machine
2. go to WP directory `/wp-content/plugins/unyson/framework/extensions`
   - if it does not exist install the "unyson" plugin first
   - full directory differs for each Wordpress install. bitnami is for example in `/opt/bitnami/wordpress/wp-content/plugins/unyson/framework/extensions`
3. download the repo manually `wget https://github.com/ThemeFuse/Unyson-Backups-Extension/archive/refs/heads/master.zip`
4. unzip the zip file `unzip master.zip`
5. rename folder to backups `mv Unyson-Backups-Extension-master/ backups`
6. clean up `rm master.zip`
7. go to your Wordpress admin panel, head over to "Unyson" and it should show "activate" at the backup  section. Click it

**Comment by davemgelinas** [comment]
Same issue here: 

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Downloading the "Backup & Demo Content" extension...

Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Downloading the "Portfolio" extension...

Failed to access Github repository "ThemeFuse/Unyson-Portfolio-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

Failed to access Github repository "ThemeFuse/Unyson-Shortcodes-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
Failed to access Github repository "ThemeFuse/Unyson-Backups-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)
Failed to access Github repository "ThemeFuse/Unyson-Portfolio-Extension" releases. (cURL error 28: Connection timed out after 5001 milliseconds)

**Comment by HumayunBA** [comment]
The issue has been solved, at least for me. I could install extensions directly this morning and it worked, but deleted all other extensions some of which were from previous versions.

**Comment by patrick-developer-77** [comment]
I'm adding what worked for me. Hopefully it works for you as well.

I de-actived the Unyson WordPress plugin and then re-activated it. Then I was able to install all of the Unyson plugins.

**Comment by mwtemplates** [comment]
Again:

```
Failed to access Github repository "ThemeFuse/Unyson-Sliders-Extension" releases. (cURL error 28: Operation timed out after 5000 milliseconds with 0 out of 0 bytes received)
```
[https://i.imgur.com/UWwl9Jl.png](https://i.imgur.com/UWwl9Jl.png)

https://github-api-cache.unyson.io/ is up now but extensions not loading

**Comment by ManySolutions** [comment]
I'm glad i kept googling. I was going mad that there was a major issue that i just couldn't get to the bottom of!
Although i have tried to install them manually via the git hub zips and that still fails me. :-/

**Comment by ManySolutions** [comment]
> Try to add following somewhere into your theme/functions.php
> 
> ```
> if ( ! function_exists( '_mwt_fw_filter_github_api_url' ) ) :
> 	function _mwt_fw_filter_github_api_url( $url ) {
> 		return 'https://api.github.com';
> 	}
> endif;
> 
> add_filter( 'fw_github_api_url', '_mwt_fw_filter_github_api_url', 999 );
> ```

Perfect. Thanks a million. :-)

**Comment by Yostina-hub** [comment]
Perfect. always you are perfect.
every my problem is solved by you

**Comment by onyagowa** [comment]
> > Try to add following somewhere into your theme/functions.php
> > ```
> > if ( ! function_exists( '_mwt_fw_filter_github_api_url' ) ) :
> > 	function _mwt_fw_filter_github_api_url( $url ) {
> > 		return 'https://api.github.com';
> > 	}
> > endif;
> > 
> > add_filter( 'fw_github_api_url', '_mwt_fw_filter_github_api_url', 999 );
> > ```
> 
> Perfect. Thanks a million. :-)



> Try to add following somewhere into your theme/functions.php
> 
> ```
> if ( ! function_exists( '_mwt_fw_filter_github_api_url' ) ) :
> 	function _mwt_fw_filter_github_api_url( $url ) {
> 		return 'https://api.github.com';
> 	}
> endif;
> 
> add_filter( 'fw_github_api_url', '_mwt_fw_filter_github_api_url', 999 );
> ```

This works perfectly, cheers mate!

**Comment by Bhanuka94** [comment]
> Try to add following somewhere into your theme/functions.php
> 
> ```
> if ( ! function_exists( '_mwt_fw_filter_github_api_url' ) ) :
> 	function _mwt_fw_filter_github_api_url( $url ) {
> 		return 'https://api.github.com';
> 	}
> endif;
> 
> add_filter( 'fw_github_api_url', '_mwt_fw_filter_github_api_url', 999 );
> ```

This worked well. Thanks for the solution.

**Comment by frankbhebhe** [comment]
> Try to add following somewhere into your theme/functions.php
> 
> ```
> if ( ! function_exists( '_mwt_fw_filter_github_api_url' ) ) :
> 	function _mwt_fw_filter_github_api_url( $url ) {
> 		return 'https://api.github.com';
> 	}
> endif;
> 
> add_filter( 'fw_github_api_url', '_mwt_fw_filter_github_api_url', 999 );
> ```

This worked thank you

**Comment by mehedialtayib** [comment]
> Try to add following somewhere into your theme/functions.php
> 
> ```
> if ( ! function_exists( '_mwt_fw_filter_github_api_url' ) ) :
> 	function _mwt_fw_filter_github_api_url( $url ) {
> 		return 'https://api.github.com';
> 	}
> endif;
> 
> add_filter( 'fw_github_api_url', '_mwt_fw_filter_github_api_url', 999 );
> ```

Best Developer Ever You Are ❤️❤️

**Comment by OusStack** [comment]
> Try to add following somewhere into your theme/functions.php
> 
> ```
> if ( ! function_exists( '_mwt_fw_filter_github_api_url' ) ) :
> 	function _mwt_fw_filter_github_api_url( $url ) {
> 		return 'https://api.github.com';
> 	}
> endif;
> 
> add_filter( 'fw_github_api_url', '_mwt_fw_filter_github_api_url', 999 );
> ```

>Thanks

**Comment by olaoluwaperfect** [comment]
> Try to add following somewhere into your theme/functions.php
> 
> ```
> if ( ! function_exists( '_mwt_fw_filter_github_api_url' ) ) :
> 	function _mwt_fw_filter_github_api_url( $url ) {
> 		return 'https://api.github.com';
> 	}
> endif;
> 
> add_filter( 'fw_github_api_url', '_mwt_fw_filter_github_api_url', 999 );
> ```

Wow! Thanks for this piece of code!

It solved my problem instantly ....
