### ISSUE TITLE
cURL error 28: Connection timed out after 5001 milliseconds

### ISSUE THREAD

**Issue by Tipsyvision** [ThemeFuse/Unyson#4360]
Describe the issue with as much details as you can. 
If it's a bug, please give the exact steps how to reproduce the problem.

Hi i just found this in the head menu were you can update the wordpress or plugins.

Unyson expention update:
Backup & Demo Content
cURL error 28: Connection timed out after 5001 milliseconds

cant update it.

**Comment by amiesass** [comment]
I am getting the same error "cURL error 28" and can't use the visual builder/brizy to update my pages any longer. It also says unyson plugin removed from wordpress but not sure if that's related. Any ideas how to fix this yet?

**Comment by Tipsyvision** [comment]
It seems to be fixed!

**Comment by sp4rky82** [comment]
My sites having the same issue. I'm getting Error 28: cURL error, connection timed out after 5001 seconds on my admin CP Dashboard. 

Also for some reason, the tabs are not loading on mobile devices, but show on Laptops. 

Can anyone advise on how to fix these issues? We're beyond desperate and don't really know what else to try. 

I seen someone mentioned, that it was fixed. I'm not the most technical person in the world, but would love some advice please if possible. 

Thanks in advance.

**Comment by sp4rky82** [comment]
> It seems to be fixed!

It's not fixed for me. I've had it a few weeks now. Any idea on now to fix it?

**Comment by amiesass** [comment]
It comes and goes for me, sometimes it shows up and sometimes it doesn’t. I don’t know how to fix it!


On Aug 15, 2024, at 9:06 PM, sp4rky82 ***@***.***> wrote:



It seems to be fixed!

It's not fixed for me. I've had it a few weeks now. Any idea on now to fix it?

**Comment by sp4rky82** [comment]
I've fixed it. Do you happen to use Namecheap hosting? It was a plugin in
the mu-plugins folder that conflicted with Unyson. Problem fixed now.

**Comment by cjdcordeiro** [comment]
It also started suddenly showing up for me.

http://github-api-cache.unyson.io seems unresponsive. Not sure that's related

**Comment by sawwd** [comment]
See my fix here https://github.com/ThemeFuse/Unyson/issues/4363#issuecomment-2324728024
