### ISSUE TITLE
Please consider shortcodes availability trough out the admin and editors independent from builder

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#756]
OK I am on shortcodes coding now after 7 months of working with Unyson and I cant shake the thought of shortcodes availability. 

Please consider the availability of Unyson shortcodes in every editor otherwise everyone that is making shortcodes for unyson has double work on their hands. 

Currently we can used them only in page builder and  blog posts ( if  builder is turned on there ) but many of us will have sliders and additional  addons where text editor are used and if we want to add our shortcodes inside we have to double code everything. 

Example ,   I am extending special heading shortcode that has about 20 different styles. It will take me about  3-5  days to finish all options and styles for it.  Nice and dandy but if I want to use those in layer slider and or slider revolution , I have to double code it and think about workarounds or introduce my own shortcode plugin next to Unyson. This make no sense. 

Now think about this , you want to 
add special heading ,  
call to action 
icon
and quote 
inside the blog post , you must turn on full blown visual editor in order to have this , 
http://prntscr.com/7whs77

Please try to do something about this since it is a huge inconvenience. 
At least give us the access to content and media elements , we dont have to have sections and columns but those tiny bits are crucial to every page, post and or sections that have editor.

**Comment by albertso** [comment]
:+1: I agree, this is quite necessary.

And, if possible, rows and columns would be nice too, why not? ;) Imagine this:


        'content' => array(
            'label' => __('Content', 'fw'),
            'type' => 'wp-editor',
            'shortcodes' => false,            // disabled (default)
            'shortcodes' => true,             // all except section, row and column
            'shortcodes' => 'all',            // full page builder
            'shortcodes' => array(            // or specify which...
                'row', 'column', 'special-header', 'call-to-action', 'button'
            ),
            'shortcodes_blacklist' => array(  // or blacklist them...
                'section','accordion', 'tabs'
            )
        )

The blacklist makes sense only if 'shortcodes' is true or 'all'.

Who doesn't want columns in a tab or slide? Please consider.

BTW, great work Unyson team! Your framework really helps me do almost everything I want in WP.
Thank you!

**Comment by danyj** [comment]
At least give us the editors buttons inside the wp-editor option , it is funny that I can see Unyson shortcodes inside avada  shortcode editor 
http://prntscr.com/82nczj
and not see them in our text block 
http://prntscr.com/82nca8

**Comment by danyj** [comment]
Please give us info on this so that we know what our next step might be. 
I now have accordions , tabs , text block and many more shortcodes that use wp-editor option , 
In NONE of those can I use button, icon, image, special heading or any other shortcodes.

**Comment by moldcraft** [comment]
At the moment I know almost nothing about wp-editor internals. It was made by I developer that left our team. So I will need to study first about wp-editor before understanding what is the problem.

**Comment by danyj** [comment]
@moldcraft  ok , fair enough , thnx for looking at it.

**Comment by danyj** [comment]
@moldcraft  heads up ,   if wp-editor option is outside builder all additional editor buttons show 
here you can see unyson and Layer slider 
http://prntscr.com/83orzn

inside builder ( or popup ) is not showing any extended editor buttons

http://prntscr.com/83osl5

**Comment by danyj** [comment]
here is test code 

	'testeditro' => array(
		'type' => 'wp-editor',
		'tinymce' => true,
		'size' => 'large',
		'reinit' => true,
		'wpautop' => false,
		'editor_height' => 100,
		'editor_type' => 'tinymce',
		'value' => 'This is dummy text',
		'label' => __('Content', 'fw')
	),

**Comment by danyj** [comment]
Can you please do something about this 

look at this 
how do you expect me to do something simple as this 
http://prntscr.com/8j5pdi

if I am not able to add icons inside text block 

http://prntscr.com/8j5qrx 

so I am forced to do this 
http://prntscr.com/8j5rbk

which ends up being something completely else 
http://prntscr.com/8j5rgx

if I cant do something simple as that without hand coding than what is the purpose of shortcodes ? 

I have been asking you for those since the beginning of the year and it was always something else in front of it , can you please look and give us a solution for this . 

For the past 3 months I am working on builder shortcodes and by the looks of this issue I have to double code all of them and create own plugin for shortcodes . Than I ask myself why code Unyson shortcodes at all than ?

**Comment by danyj** [comment]
@moldcraft  @llemurya  suggestion , create own option name 

fw-editor that will let us see the shortcodes if you are not able to fix the default wp-editor option

**Comment by DimiBaitanciuc** [comment]
Hey, 

I get that you are a little frustrated and I'm sorry about it but look what I've done in 2 min: http://joxi.ru/zANBp7Miwa1QA9 the exact same thing you want. You just need to enter into design mode and think more in terms of design (sections and columns) rather then having all of the elements in one shortcode. Of course with basic HTML you could have inserted the <img> right there, but there is no need for that.

Look how my back end shortcode structure looks like: http://joxi.ru/RmzQKjBfV3VvrO 

Hope this helps.

**Comment by danyj** [comment]
@DimiBaitanciuc  bud , I can do that with many workarounds just like you did  , but none of workarounds should be used there , it is a simple icon/button/image that we should be able to place in without additional maze structure. ,  now  go and resize your screen and all that will start drooping under each-other for no good reason. this  should be plain text mode , one liner not a column div structure

**Comment by danyj** [comment]
and now I should make a space shortcode for it right ?  cmon ,  I understand that you are trying  to help here but this is not how that should be done .   ANY crappy framework gives you an option to add their own shortcode inside a text or gives you those from wp-editor ,  WE ( Unyson ) dont have a crappy framework , it is state of the art , but this has somehow slipped the option/extension developers mind and it should be fixed.

**Comment by danyj** [comment]
@DimiBaitanciuc  I said before , since I knew that section/column might be an issue ,  give us the content and media elements ,  I can care less about   section in section or column in column 

P.S. dont take my way of saying things to harsh please , I am brainstorming and this is just in my way since few months.

**Comment by DimiBaitanciuc** [comment]
No worries we all want the same thing here. As I understand from our developers, this is on the list so if it's on the list it will be done. 

As for the time line can't put my finger on it, we are working on the Backup extension right now have some things to do there and soon after that we will look over this.

Don't know how to help more sorry :(

**Comment by danyj** [comment]
timeline is not important  at this very moment, I wont be done for few more months , this is huge project . all I need to do is plan , and if you say it will be in than I can take a brake and plan something else instead of thinking to make a shrotcodes plugin.

**Comment by jonmlas** [comment]
still waiting for this to happen...

**Comment by danyj** [comment]
if only the editor were fixed https://github.com/ThemeFuse/Unyson/issues/756#issuecomment-129212311 to show the unyson shortcodes button we would be done with this

**Comment by moldcraft** [comment]
Option-type wp-editor was [fixed](https://github.com/ThemeFuse/Unyson/compare/87675985308a15da80e3167638a388647da50539...59c0d00f8c75f0b99c3b83cd31f63b06374a77a5?diff=split&name=59c0d00f8c75f0b99c3b83cd31f63b06374a77a5), it should integrate well with other wp-editor plugins (which add more functionality/buttons to it). Unfortunately the Unyson Shortcodes button at the moment it's impossible to make it work because it saves the value in post meta not in actual wp-editor text value, so it works only in main post content wp-editor.

I will try to make it save the value inside the textarea, but at the moment I don't know how to do it (and if it's possible), so this feature will not be implemented soon.

**Comment by danyj** [comment]
editor shortcodes feature should have been standalone from the beginning and something like this is vital for any theme. without it we are forced to make own plugins to have Unyson shortcodes we worked on so long available in any editor. 

This was a huge miss on dev who made it and we are dancing around this since the actual feature release which was more than a year ago. So a rework or editor shortcodes 2 should be the next step. 

I know that you are  busy but again , we all started complaining  since this thing came out. That should have been enough to set the priority.

**Comment by dinhtungdu** [comment]
The button already work with wp-option type, it doesn't show in wp-editor option type because the page builder does not allow that.
I digged in `plugin.js` file, allow button to insert to wp-editor options, and it worked! Simple! Commit here: #7a886f9
The only problem remaining is that wp-editor did not support shortcode out of the box. We need help of `do_shortcode` in template to make shortcode work.

**Comment by andreiglingeanu** [comment]
Great it is closed :)
